### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by Passiday** [donwojtallo/ev3dev-snake-js#3]
Well, I am aware that 2 years have passed, I just though I'd use your project to test the ev3dev capabilities, but I could not build it:

```
robot@ev3dev:~/ev3dev-snake-js$ npm install
\
> ioctl@2.0.0 install /home/robot/ev3dev-snake-js/node_modules/ioctl
> node-gyp rebuild

make: Entering directory '/home/robot/ev3dev-snake-js/node_modules/ioctl/build'
  CXX(target) Release/obj.target/ioctl/src/ioctl.o
../src/ioctl.cpp:44:9: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
         return Nan::ThrowError(Nan::ErrnoException(errno, "ioctl", nullptr, nullptr));
         ^
In file included from ../src/ioctl.cpp:3:0:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
../src/ioctl.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Ioctl(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ioctl.cpp:44:68: error: ‘nullptr’ was not declared in this scope
         return Nan::ThrowError(Nan::ErrnoException(errno, "ioctl", nullptr, nullptr));
                                                                    ^
../src/ioctl.cpp:44:85: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return Nan::ThrowError(Nan::ErrnoException(errno, "ioctl", nullptr, nullptr));
                                                                                     ^
ioctl.target.mk:82: recipe for target 'Release/obj.target/ioctl/src/ioctl.o' failed
make: *** [Release/obj.target/ioctl/src/ioctl.o] Error 1
make: Leaving directory '/home/robot/ev3dev-snake-js/node_modules/ioctl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.32-17-ev3dev-ev3
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/robot/ev3dev-snake-js/node_modules/ioctl
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! ioctl@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ioctl@2.0.0 install script.
npm ERR! This is most likely a problem with the ioctl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ioctl
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.32-17-ev3dev-ev3
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/robot/ev3dev-snake-js
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/robot/ev3dev-snake-js/npm-debug.log
npm ERR! not ok code 0
```

**Comment by donwojtallo** [comment]
Hello.
Sadly, I have no time to maintain this project anymore, but it looks like, there is a problem with `ioctl` library. Try to update version in package.json or use old compiled version included in `1.0.1` release of this project.
https://github.com/donwojtallo/ev3dev-snake-js/releases/download/v1.0.1-beta/ev3dev-snake-js-with-modules-v1.0.1-beta.tar.gz.
Hope it helps.

**Comment by Passiday** [comment]
Ok, I've got it running:

1) Just changing the ioctl version to 1.0.1 in package.json did not do the
trick. I removed it from the package.json and copied the folder from your
v1.0.1-beta release
2) For some reason, the classes/led.js was requiring "ev3dev" instead of
"ev3dev-lang", that had to be fixed
3) The LED inits in led.js apparently use old-style device names: instead
of "ev3:green:left" there has to be "ev3:left:green" (4 vars)

Those are very simple changes, so you might want to make a commit for them,
in a separate branch, so that EV3 enthusiasts can have their peace :)

**Comment by donwojtallo** [comment]
Thanks! I will commit this changes soon.
P.S. `ev3dev` was working 2 years ago, with old names `ev3:green:left`.

**Comment by donwojtallo** [comment]
I see I made a mistake by changing package dependencies some time ago and not updating `led.js`. I have commited changes to master branch, it should be done months ago.
